language: java
jdk: openjdk7
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "
if [ ${TRAVIS_PULL_REQUEST} = 'false' ];
then
    mvn clean deploy --settings target/travis/settings.xml;
else
    mvn clean install --settings target/travis/settings.xml;
fi"

# whitelist
branches:
  only:
    - develop

notifications:
  hipchat:
    rooms:
      secure: EiS9Vejix11+WWZRuxwMLdTPfxz7M+4cUzmrBfYN2rRhLrT2DrEDzhYpzxJ0lWvrIDdrZMqrAhw2PZVcNl0hvShnbyTSOkufXzSDxpD2eOIO6XxdPgZYasvPU/CmlXLpFL7fX0AGmrueFsNBlhIPBH0l/YWyEHtRZ7nlmixGrds=
env:
  global:
  - secure: HqbtFQy5zFN8RXrMm19x2FIOYPpDe58J/LTKDYcYiTrbiQ2zWCr+mngy5sJib314wDbueW427d5Ob//ctNOjw/bhdCPuE1VHibN2qUJXKmziIay+fvxsjLtGJQGjgnnbFHHmuK030HO922HpBrSMqkcQ477GW65Q24eFACEiwbs=
  - secure: Cgwms17ZG2O6t16I8Ba6KmMgbIgLyD26mS+DPDgRDTX9eFtULx+GEUd9kYgLhWdHVvH5Wy6jLhtgHWff9UZETSXWDbKcF3Fjq74fgTHDNV9y2qsUfUT/TAuwAiW+mIE9k/XGbn98kVHr6iEODIL35xjSAeOPzcnfY4aGBaIa0Ig=


#mvn -Prelease -DnewVersion=1.0.${TRAVIS_BUILD_NUMBER} initialize --settings target/travis/settings.xml;
