language: java
jdk: openjdk7
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
script: "
if [ ${TRAVIS_PULL_REQUEST} = 'false' ];
then
    mvn clean deploy --settings target/travis/settings.xml;
else
    mvn clean verify --settings target/travis/settings.xml;
fi"

# whitelist
branches:
  only:
    - develop

notifications:
  hipchat:
    rooms:
      secure: EiS9Vejix11+WWZRuxwMLdTPfxz7M+4cUzmrBfYN2rRhLrT2DrEDzhYpzxJ0lWvrIDdrZMqrAhw2PZVcNl0hvShnbyTSOkufXzSDxpD2eOIO6XxdPgZYasvPU/CmlXLpFL7fX0AGmrueFsNBlhIPBH0l/YWyEHtRZ7nlmixGrds=
env:
  global:
  - secure: MIZ5ff1hk6v79Nutc2RMdJlinSwL5HHHrY+qhixQb2xa5B2kJCifSgrWeahQSf4tA07489pyhGaHYKckKAtNpmnel/KK5VmpaUBIYj5ypk4ybz+wO9GRdNjYVRk+9yLZ5qGRfsJ4+QsszKOpT2IFt6fPjUX/IgJvySqTtqBzGEg=
  - secure: ZKlKf8+yfXVA08TSTBmOMltsxez1yFuyPwge+rnPq/FPKLxp+otgSQ5Yn3dfOFeKVsMdU3nMw8FxdoN2c5abH2FnzCFU/LfloXMM15f30c9Eui3n0EZlKYpITOFbPSnQfGwOiYyangb2AVXqnNClyrX0dGB8oHg3ncRf7nBqKeg=
