language: java
jdk: oraclejdk7
script: mvn -B install
notifications:
  hipchat:
    rooms:
      secure: g/k7byjQjbxho4lwDaq5N6XT+dvhVS0yuUm9HtbfjXRuxz3oQt7gO/q6KJp1ZbU+Q08GsjBGN0mu6ICtco4tOrK3nRqU55PpZwqXngERy4XGQZzUvZQ9ZIbD2JMtLo4CBacC8N56vKxsIqDYpB2lMvOilNeHv1GJUT9dio0ho8M=
